### ISSUE TITLE
Error when import

### ISSUE THREAD

**Issue by paulocoutinhox** [lukeed/totalist#5]
Hi,

Im getting error when import:

```


(node:1481) ExperimentalWarning: The ESM module loader is experimental.
--
03:33:01.018 | file:///opt/buildhome/repo/bin/config/copy.js:5
03:33:01.018 | import { totalist } from 'totalist';
03:33:01.018 | ^^^^^^^^
03:33:01.018 | SyntaxError: The requested module 'totalist' does not provide an export named 'totalist'
03:33:01.018 | at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
03:33:01.018 | at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
03:33:01.018 | at async Loader.import (internal/modules/esm/loader.js:179:24)
03:33:01.023 | npm ERR! code ELIFECYCLE


```

**Comment by lukeed** [comment]
Totalist only moved to a named exports for 2.0.0
If you're using an earlier version, you need to use a default import instead:

```js
import totalist from "totalist";
```

This was the breaking change that prompted a new major version.

Hope that helps
